### ISSUE TITLE
Support top level `enum` type

### ISSUE THREAD

**Issue by colinterface** [joewood/avro-typescript#10]
First of all, thanks for the the awesome tool!

I'm encountering an error that prevents me from adopting it.

Given the following `example.avdl`
```
enum CompanySize {
  SMALL,
  MEDIUM,
  LARGE
}
```

Which `avro-tools` generates into the following `CompanySize.avsc`
```
{
  "type": "enum",
  "name": "CompanySize",
  "namespace": "com.example.avro",
  "symbols": ["SMALL", "MEDIUM", "LARGE"]
}
```

When I convert with the following script
```
const schemaText = fs.readFileSync("CompanySize.avsc", "UTF8");
const schema = JSON.parse(schemaText);
const interface = avroToTypeScript(schema);
```

I get the following error 
```
/Users/colin/play/avro-ts/node_modules/avro-typescript/lib/index.js:41
    for (var _i = 0, _a = recordType.fields; _i < _a.length; _i++) {
                                                     ^

TypeError: Cannot read property 'length' of undefined
    at convertRecord (/Users/colin/play/avro-ts/node_modules/avro-typescript/lib/index.js:41:54)
```

Would you be open to a contribution that handles `enum` as a top level type in addition to the `record` type?

**Comment by colinterface** [comment]
Hm, maybe I have the wrong idea. Seems like maybe the idea is to only parse and convert a single top level record, since the `.avsc` includes all of its own dependencies.

For example, the full `example.avdl`
```
@namespace("com.example.avro")
protocol ExampleProtocol {
  enum CompanySize {
    SMALL,
    MEDIUM,
    BIG
  }
  record CompanyRecord {
    string name;
    CompanySize size;
    string countryCode;
  }
}
```

Generates the following `CompanyRecord.avsc` in addition to `CompanySize.avsc`

```
{
  "type" : "record",
  "name" : "CompanyRecord",
  "namespace" : "com.example.avro",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "size",
    "type" : {
      "type" : "enum",
      "name" : "CompanySize",
      "symbols" : [ "SMALL", "MEDIUM", "BIG" ]
    }
  }, {
    "name" : "countryCode",
    "type" : "string"
  } ]
}
```

Which is correctly converted into TS.

I'm trying to set up a pipeline that converts `.avdl` into classes/interfaces in various languages. Maybe I'm just using the `avro-tools` IDL -> schema conversion CLI wrong

**Comment by joewood** [comment]
Top level enums should now be support in version 1.1. I added a test for it too in the test suite. Let me know if that works.
