### ISSUE TITLE
The typescript schema is not generated correctly for array of union types

### ISSUE THREAD

**Issue by fredfort** [joewood/avro-typescript#3]
Hello, 
Thanks for this library!

I think there is an issue with array of union types

Avro schema:
```
{
  "type": "record",
  "name": "ExampleType",
  "fields": [{ 
    "name": "arrayUnion", 
    "type":{
      "type": "array",
      "items": ["string", "int"]
    }
  }]
}
```

Generated output:
```
export interface ExampleType {
        arrayUnion: string | number[];
}
```
The arrayUnion can then be a **string** or an **array of number**, whereas it should to be an **array of string** or an **array of number** like so:
```
export interface ExampleType {
        arrayUnion: (string | number)[];
}
```

I can create a PR if needed.

Thanks, 

Fred

**Comment by fredfort** [comment]
I actually created a fork fixing the issue and adding some new features specific to my needs:

https://github.com/fredfort/avro-typescript

Thanks again for this library!

Fred.

**Comment by aleccool213** [comment]
@fredfort you should make a pr :)
