### ISSUE TITLE
Library release ?

### ISSUE THREAD

**Issue by iangregsondev** [joewood/avro-typescript#9]
Hi @joewood , in march you merged a pull request. https://github.com/joewood/avro-typescript/pull/6

I noticed that nothing was released on NPM - so do an npm install, this is not available.

Do you plan on releasing it?

The last release is 3 years ago - I believe. https://www.npmjs.com/package/avro-typescript

Thanks

**Comment by iangregsondev** [comment]
IN the meantime, I was able to install it using the following

```
npm install github:joewood/avro-typescript#6dffae1e4fa6d70f59e73537271f1a704a026e41 -D
```

in case anybody else needs it.

**Comment by joewood** [comment]
Should be released now. Let me know if you can't see it.
